import type { Product, Category } from "./types"

export const categories: Category[] = [
  { id: "1", name: "Snacks", slug: "snacks" },
  { id: "2", name: "Fruits and Vegetables", slug: "fruits-vegetables" },
  { id: "3", name: "Beverages", slug: "beverages" },
  { id: "4", name: "Packaged Food", slug: "packaged-food" },
  { id: "5", name: "Canned Food", slug: "canned-food" },
  { id: "6", name: "Pulses and Grains", slug: "pulses-grains" },
  { id: "7", name: "Dairy", slug: "dairy" },
  { id: "8", name: "Spices", slug: "spices" },
  { id: "9", name: "Meat", slug: "meat" },
  { id: "10", name: "Frozen Food", slug: "frozen-food" },
  { id: "11", name: "Household", slug: "household" },
  { id: "12", name: "Stationary", slug: "stationary" },
  { id: "13", name: "Electronics", slug: "electronics" },
  { id: "14", name: "Men Clothes", slug: "men-clothes" },
  { id: "15", name: "Women Clothes", slug: "women-clothes" },
  { id: "16", name: "Kids Clothes", slug: "kids-clothes" },
]

export const allProducts: Product[] = [
  // SNACKS - Updated with your new items
  {
    id: "snacks-1",
    name: "Lay's Classic",
    price: 1.49,
    originalPrice: 1.79,
    discount: 17,
    image: "/images/lays.png",
    category: "snacks",
    inStock: true,
    rating: 4,
    reviews: 25,
  },
  {
    id: "snacks-2",
    name: "Doritos Nacho Cheese",
    price: 1.79,
    originalPrice: 2.29,
    discount: 22,
    image: "/images/dorito.png",
    category: "snacks",
    inStock: true,
    rating: 5,
    reviews: 32,
  },
  {
    id: "snacks-3",
    name: "Pringles Original",
    price: 2.29,
    originalPrice: 2.99,
    discount: 23,
    image: "/images/pringle.png",
    category: "snacks",
    inStock: true,
    rating: 4,
    reviews: 18,
  },
  {
    id: "snacks-4",
    name: "Oreo Original",
    price: 2.99,
    originalPrice: 3.49,
    discount: 14,
    image: "/images/oreo.png",
    category: "snacks",
    inStock: true,
    rating: 5,
    reviews: 45,
  },
  {
    id: "snacks-5",
    name: "Parle-G",
    price: 0.99,
    originalPrice: 1.29,
    discount: 23,
    image: "/images/parleg.png",
    category: "snacks",
    inStock: true,
    rating: 4,
    reviews: 28,
  },
  {
    id: "snacks-6",
    name: "McVitie's Digestives",
    price: 3.49,
    originalPrice: 4.29,
    discount: 19,
    image: "/images/mcveti.png",
    category: "snacks",
    inStock: true,
    rating: 4,
    reviews: 15,
  },
  {
    id: "snacks-7",
    name: "Hershey's Milk Chocolate",
    price: 1.25,
    originalPrice: 1.59,
    discount: 21,
    image: "/images/harshey.png",
    category: "snacks",
    inStock: true,
    rating: 5,
    reviews: 38,
  },
  {
    id: "snacks-8",
    name: "Snickers Bar",
    price: 1.15,
    originalPrice: 1.49,
    discount: 23,
    image: "/images/snicker.png",
    category: "snacks",
    inStock: true,
    rating: 5,
    reviews: 42,
  },
  

  // FRUITS AND VEGETABLES
  {
    id: "fruits-1",
    name: "Fresh Organic Bananas (1 lb)",
    price: 2.99,
    originalPrice: 3.99,
    discount: 25,
    image: "/images/banana.png",
    category: "fruits-vegetables",
    inStock: true,
    rating: 4,
    reviews: 15,
  },
  {
    id: "fruits-2",
    name: "Fresh Organic Apples (1 lb)",
    price: 3.49,
    originalPrice: 4.29,
    discount: 19,
    image: "/images/apple.png",
    category: "fruits-vegetables",
    inStock: true,
    rating: 5,
    reviews: 22,
  },

  {
    id: "fruits-3",
    name: "Fresh Organic Potato (1 lb)",
    price: 2.79,
    originalPrice: 3.49,
    discount: 20,
    image: "/images/potato.png",
    category: "fruits-vegetables",
    inStock: true,
    rating: 4,
    reviews: 9,
  },
  {
    id: "fruits-4",
    name: "Fresh Organic Carrots (1 lbs)",
    price: 1.99,
    originalPrice: 2.49,
    discount: 20,
    image: "/images/carrot.png",
    category: "fruits-vegetables",
    inStock: true,
    rating: 5,
    reviews: 14,
  },
  {
    id: "fruits-5",
    name: "Fresh Spinach leaves (1 lb)",
    price: 2.49,
    originalPrice: 4.29,
    discount: 19,
    image: "/images/spinach.png",
    category: "fruits-vegetables",
    inStock: true,
    rating: 5,
    reviews: 22,
  },
  {
    id: "fruits-6",
    name: "Fresh Organic Tomato (1 lb)",
    price: 2.86,
    originalPrice: 3.29,
    discount: 19,
    image: "/images/tomato.png",
    category: "fruits-vegetables",
    inStock: true,
    rating: 5,
    reviews: 22,
  },
  {
    id: "fruits-7",
    name: "Fresh Strawberries (1 lb)",
    price: 2.86,
    originalPrice: 3.29,
    discount: 19,
    image: "/images/straw.png",
    category: "fruits-vegetables",
    inStock: true,
    rating: 5,
    reviews: 22,
  },
  {
    id: "fruits-8",
    name: "Fresh Mango (1 lb)",
    price: 2.86,
    originalPrice: 3.29,
    discount: 19,
    image: "/images/mango.png",
    category: "fruits-vegetables",
    inStock: true,
    rating: 5,
    reviews: 22,
  },


  // BEVERAGES
  {
    id: "beverages-1",
    name: "Nestle Original Coffee-Mate Coffee Creamer",
    price: 11.99,
    originalPrice: 13.99,
    discount: 50,
    image: "/images/coffee.png",
    category: "beverages",
    inStock: true,
    rating: 5,
    reviews: 1,
  },
  {
    id: "beverages-2",
    name: "Coca-Cola Classic (12 pack)",
    price: 5.99,
    originalPrice: 7.49,
    discount: 20,
    image: "/images/cc.png",
    category: "beverages",
    inStock: true,
    rating: 5,
    reviews: 35,
  },
  {
    id: "beverages-3",
    name: "Tropicana Orange Juice",
    price: 4.29,
    originalPrice: 5.99,
    discount: 28,
    image: "/images/torange.png",
    category: "beverages",
    inStock: true,
    rating: 4,
    reviews: 16,
  },
  {
    id: "beverages-4",
    name: "Tropicana Apple Juice",
    price: 8.99,
    originalPrice: 10.99,
    discount: 18,
    image: "/images/tapple.png",
    category: "beverages",
    inStock: true,
    rating: 5,
    reviews: 28,
  },

  // PACKAGED FOOD
  {
    id: "packaged-1",
    name: "Bambino Pasta",
    price: 1.29,
    originalPrice: 1.79,
    discount: 28,
    image: "/images/pasta.png",
    category: "packaged-food",
    inStock: true,
    rating: 4,
    reviews: 42,
  },
  {
    id: "packaged-2",
    name: "Kissan ketchup",
    price: 1.99,
    originalPrice: 2.49,
    discount: 20,
    image: "/images/ketchup.png",
    category: "packaged-food",
    inStock: true,
    rating: 4,
    reviews: 18,
  },
  {
    id: "packaged-3",
    name: "Barilla Spaghetti Pasta",
    price: 1.49,
    originalPrice: 1.99,
    discount: 25,
    image: "/images/spagetti.png",
    category: "packaged-food",
    inStock: true,
    rating: 5,
    reviews: 31,
  },
  {
    id: "packaged-4",
    name: "Great Value cocoa powder ",
    price: 2.79,
    originalPrice: 3.29,
    discount: 15,
    image: "/images/cocoa.png",
    category: "packaged-food",
    inStock: true,
    rating: 4,
    reviews: 12,
  },
  {
    id: "packaged-5",
    name: "Great Value baking powder ",
    price: 2.79,
    originalPrice: 3.29,
    discount: 15,
    image: "/images/bpowder.png",
    category: "packaged-food",
    inStock: true,
    rating: 4,
    reviews: 12,
  },
  {
    id: "packaged-6",
    name: "Kraft Mac & Cheese",
    price:  1.79,
    image: "/images/mac.png",
    category: "packaged-food",
    inStock: true,
    rating: 4,
    reviews: 12,
  },
  {
    id: "packaged-7",
    name: "Instant Ramen (Nissin Cup Noodles)",
    price:  1.29,
    image: "/images/cup.png",
    category: "packaged-food",
    inStock: true,
    rating: 4,
    reviews: 12,
  },
  {
    id: "packaged-8",
    name: "Maggi Family pack",
    price:  2.45,
    image: "/images/maggi.png",
    category: "packaged-food",
    inStock: true,
    rating: 4,
    reviews: 12,
  },

  // CANNED FOOD
  {
    id: "canned-1",
    name: "Fillipo Berio Olive Oil",
    price: 0.99,
    originalPrice: 1.29,
    discount: 23,
    image: "/images/olive.png",
    category: "canned-food",
    inStock: true,
    rating: 4,
    reviews: 24,
  },
  {
    id: "canned-2",
    name: "Watkins Vanilla Extract",
    price: 1.49,
    originalPrice: 1.89,
    discount: 21,
    image: "/images/vanilla.png",
    category: "canned-food",
    inStock: true,
    rating: 4,
    reviews: 15,
  },
  {
    id: "canned-3",
    name: "Del Monte Corn Kernels",
    price: 1.79,
    originalPrice: 2.29,
    discount: 22,
    image: "/images/corn.png",
    category: "canned-food",
    inStock: true,
    rating: 5,
    reviews: 19,
  },
  {
    id: "canned-4",
    name: "Bush's Baked Beans",
    price: 2.29,
    originalPrice: 2.79,
    discount: 18,
    image: "/images/bean.png",
    category: "canned-food",
    inStock: true,
    rating: 4,
    reviews: 11,
  },

  // PULSES AND GRAINS
  {
    id: "pulses-1",
    name: "All-purpose Flour (2 lbs)",
    price: 8.99,
    originalPrice: 12.99,
    discount: 30,
    image: "/images/flour.png",
    category: "pulses-grains",
    inStock: true,
    rating: 5,
    reviews: 8,
  },
  {
    id: "pulses-2",
    name: "Red Masoor dal (2 lbs)",
    price: 3.99,
    originalPrice: 4.99,
    discount: 20,
    image: "/images/red.png",
    category: "pulses-grains",
    inStock: true,
    rating: 4,
    reviews: 13,
  },
  {
    id: "pulses-3",
    name: "Quinoa Organic (1 lb)",
    price: 6.99,
    originalPrice: 8.99,
    discount: 22,
    image: "/images/quinoa.png",
    category: "pulses-grains",
    inStock: true,
    rating: 5,
    reviews: 17,
  },
  {
    id: "pulses-4",
    name: "Black Lentils (2 lbs)",
    price: 4.49,
    originalPrice: 5.99,
    discount: 25,
    image: "/images/black.png",
    category: "pulses-grains",
    inStock: true,
    rating: 4,
    reviews: 9,
  },

  // DAIRY
  {
    id: "dairy-1",
    name: "Eggs (1 dozen) ",
    price: 5.49,
    image: "/images/egg.png",
    category: "dairy",
    inStock: true,
    rating: 5,
    reviews: 1,
  },
  {
    id: "dairy-2",
    name: "Organic Whole Milk (1 gallon)",
    price: 4.99,
    originalPrice: 5.99,
    discount: 17,
    image: "/images/milk.png",
    category: "dairy",
    inStock: true,
    rating: 5,
    reviews: 23,
  },
  {
    id: "dairy-3",
    name: "Greek Yogurt Plain (32 oz)",
    price: 5.49,
    originalPrice: 6.99,
    discount: 21,
    image: "/images/yogurt.png",
    category: "dairy",
    inStock: true,
    rating: 4,
    reviews: 18,
  },
  {
    id: "dairy-4",
    name: "Organic Butter (1 lb)",
    price: 6.99,
    originalPrice: 8.49,
    discount: 18,
    image: "/images/butter.png",
    category: "dairy",
    inStock: true,
    rating: 5,
    reviews: 14,
  },

  // SPICES
  {
    id: "spices-1",
    name: "Himalayan Table salt (1kg)",
    price: 3.99,
    originalPrice: 4.99,
    discount: 20,
    image: "/images/salt.png",
    category: "spices",
    inStock: true,
    rating: 5,
    reviews: 16,
  },
  {
    id: "spices-2",
    name: "Granulated Sugar (1kg)",
    price: 5.99,
    originalPrice: 7.99,
    discount: 25,
    image: "/images/sugar.png",
    category: "spices",
    inStock: true,
    rating: 5,
    reviews: 21,
  },
  {
    id: "spices-3",
    name: "Organic Turmeric Powder",
    price: 4.49,
    originalPrice: 5.99,
    discount: 25,
    image: "/images/turmeric.png",
    category: "spices",
    inStock: true,
    rating: 4,
    reviews: 12,
  },
  {
    id: "spices-4",
    name: "Italian Seasoning Blend",
    price: 2.99,
    originalPrice: 3.99,
    discount: 25,
    image: "/images/oregano.png",
    category: "spices",
    inStock: true,
    rating: 4,
    reviews: 8,
  },

  // MEAT
  {
    id: "meat-1",
    name: "All Natural Italian-Style Chicken Meatballs",
    price: 7.25,
    originalPrice: 9.35,
    discount: 22,
    image: "/images/balls.png",
    category: "meat",
    inStock: true,
    rating: 4,
    reviews: 1,
  },
  {
    id: "meat-2",
    name: "Ground Beef 80/20 (1 lb)",
    price: 5.99,
    originalPrice: 7.49,
    discount: 20,
    image: "/images/beef.png",
    category: "meat",
    inStock: true,
    rating: 4,
    reviews: 19,
  },
  {
    id: "meat-3",
    name: "Chicken Breast Boneless (2 lbs)",
    price: 8.99,
    originalPrice: 11.99,
    discount: 25,
    image: "/images/chicken.png",
    category: "meat",
    inStock: true,
    rating: 5,
    reviews: 27,
  },
  {
    id: "meat-4",
    name: "Salmon Fillet Fresh (1 lb)",
    price: 12.99,
    originalPrice: 15.99,
    discount: 19,
    image: "/images/fish.png",
    category: "meat",
    inStock: true,
    rating: 5,
    reviews: 15,
  },

  // FROZEN FOOD
  {
    id: "frozen-1",
    name: "Frozen Mixed Vegetables",
    price: 2.99,
    originalPrice: 3.99,
    discount: 25,
    image: "/images/veg.png",
    category: "frozen-food",
    inStock: true,
    rating: 4,
    reviews: 13,
  },
  {
    id: "frozen-2",
    name: "Ben & Jerry's Ice Cream",
    price: 4.99,
    originalPrice: 6.99,
    discount: 29,
    image: "/images/taj.png",
    category: "frozen-food",
    inStock: true,
    rating: 5,
    reviews: 34,
  },
  {
    id: "frozen-3",
    name: "Frozen Pizza Margherita",
    price: 3.99,
    originalPrice: 5.49,
    discount: 27,
    image: "/images/pizza.png",
    category: "frozen-food",
    inStock: true,
    rating: 4,
    reviews: 22,
  },
  {
    id: "frozen-4",
    name: "Frozen French Fries",
    price: 2.49,
    originalPrice: 3.29,
    discount: 24,
    image: "/images/fries.png",
    category: "frozen-food",
    inStock: true,
    rating: 4,
    reviews: 18,
  },

  // HOUSEHOLD
  {
    id: "household-1",
    name: "Tide Laundry Detergent",
    price: 12.99,
    originalPrice: 15.99,
    discount: 19,
    image: "/images/tide.png",
    category: "household",
    inStock: true,
    rating: 5,
    reviews: 28,
  },
  {
    id: "household-2",
    name: "Charmin Toilet Paper (12 rolls)",
    price: 8.99,
    originalPrice: 11.99,
    discount: 25,
    image: "/images/tpaper.png",
    category: "household",
    inStock: true,
    rating: 5,
    reviews: 41,
  },
  {
    id: "household-3",
    name: "Dawn Dish Soap",
    price: 3.99,
    originalPrice: 4.99,
    discount: 20,
    image: "/images/dishwash.png",
    category: "household",
    inStock: true,
    rating: 5,
    reviews: 19,
  },
  {
    id: "household-4",
    name: "Lysol Disinfectant Spray",
    price: 4.49,
    originalPrice: 5.99,
    discount: 25,
    image: "/images/lysol.png",
    category: "household",
    inStock: true,
    rating: 4,
    reviews: 16,
  },

  // STATIONARY
  {
    id: "stationary-1",
    name: "BIC Ballpoint Pens (10 pack)",
    price: 3.99,
    originalPrice: 5.99,
    discount: 33,
    image: "/images/pen.png",
    category: "stationary",
    inStock: true,
    rating: 4,
    reviews: 12,
  },
  {
    id: "stationary-2",
    name: "Spiral Notebooks (5 pack)",
    price: 7.99,
    originalPrice: 9.99,
    discount: 20,
    image: "/images/books.png",
    category: "stationary",
    inStock: true,
    rating: 4,
    reviews: 8,
  },
  {
    id: "stationary-3",
    name: "Scotch Tape Dispenser",
    price: 4.99,
    originalPrice: 6.99,
    discount: 29,
    image: "/images/tape.png",
    category: "stationary",
    inStock: true,
    rating: 5,
    reviews: 14,
  },
  {
    id: "stationary-4",
    name: "Post-it Sticky Notes",
    price: 5.49,
    originalPrice: 7.99,
    discount: 31,
    image: "/images/sticky.png",
    category: "stationary",
    inStock: true,
    rating: 5,
    reviews: 22,
  },

  // ELECTRONICS
  {
    id: "electronics-1",
    name: "USB-C Charging Cable",
    price: 12.99,
    originalPrice: 19.99,
    discount: 35,
    image: "/images/usb.png",
    category: "electronics",
    inStock: true,
    rating: 4,
    reviews: 18,
  },
  {
    id: "electronics-2",
    name: "Bluetooth Wireless Earbuds",
    price: 29.99,
    originalPrice: 49.99,
    discount: 40,
    image: "/images/earbud.png",
    category: "electronics",
    inStock: true,
    rating: 4,
    reviews: 25,
  },
  {
    id: "electronics-3",
    name: "Portable Phone Charger",
    price: 19.99,
    originalPrice: 29.99,
    discount: 33,
    image: "/images/charger.png",
    category: "electronics",
    inStock: true,
    rating: 5,
    reviews: 31,
  },
  {
    id: "electronics-4",
    name: "LED Desk Lamp",
    price: 24.99,
    originalPrice: 34.99,
    discount: 29,
    image: "/images/lamp.png",
    category: "electronics",
    inStock: true,
    rating: 4,
    reviews: 16,
  },

  // MEN CLOTHES
  {
    id: "men-clothes-1",
    name: "Men's Cotton T-Shirt",
    price: 14.99,
    originalPrice: 19.99,
    discount: 25,
    image: "/images/mentshirt.png",
    category: "men-clothes",
    inStock: true,
    rating: 4,
    reviews: 23,
  },
  {
    id: "men-clothes-2",
    name: "Men's Denim Jeans",
    price: 39.99,
    originalPrice: 59.99,
    discount: 33,
    image: "/images/jean.png",
    category: "men-clothes",
    inStock: true,
    rating: 5,
    reviews: 18,
  },
  {
    id: "men-clothes-3",
    name: "Men's Polo Shirt",
    price: 24.99,
    originalPrice: 34.99,
    discount: 29,
    image: "/images/polo.png",
    category: "men-clothes",
    inStock: true,
    rating: 4,
    reviews: 15,
  },
  {
    id: "men-clothes-4",
    name: "Men's Casual Sneakers",
    price: 49.99,
    originalPrice: 79.99,
    discount: 38,
    image: "/images/menshoes.png",
    category: "men-clothes",
    inStock: true,
    rating: 5,
    reviews: 27,
  },

  // WOMEN CLOTHES
  {
    id: "women-clothes-1",
    name: "Women's Floral Dress",
    price: 34.99,
    originalPrice: 49.99,
    discount: 30,
    image: "/images/floral.png",
    category: "women-clothes",
    inStock: true,
    rating: 5,
    reviews: 19,
  },
  {
    id: "women-clothes-2",
    name: "Women's Skinny Jeans",
    price: 29.99,
    originalPrice: 44.99,
    discount: 33,
    image: "/images/skinny.png",
    category: "women-clothes",
    inStock: true,
    rating: 4,
    reviews: 22,
  },
  {
    id: "women-clothes-3",
    name: "Women's Cardigan Sweater",
    price: 39.99,
    originalPrice: 59.99,
    discount: 33,
    image: "/images/cardigan.png",
    category: "women-clothes",
    inStock: true,
    rating: 5,
    reviews: 14,
  },
  {
    id: "women-clothes-4",
    name: "Women's Running Shoes",
    price: 54.99,
    originalPrice: 89.99,
    discount: 39,
    image: "/images/shoe.png",
    category: "women-clothes",
    inStock: true,
    rating: 5,
    reviews: 31,
  },

  // KIDS CLOTHES
  {
    id: "kids-clothes-1",
    name: "Kids' Cartoon T-Shirt",
    price: 9.99,
    originalPrice: 14.99,
    discount: 33,
    image: "/images/cartoon.png",
    category: "kids-clothes",
    inStock: true,
    rating: 4,
    reviews: 16,
  },
  {
    id: "kids-clothes-2",
    name: "Kids' Denim Overalls",
    price: 19.99,
    originalPrice: 29.99,
    discount: 33,
    image: "/images/denim.png",
    category: "kids-clothes",
    inStock: true,
    rating: 5,
    reviews: 12,
  },
  {
    id: "kids-clothes-3",
    name: "Kids' Winter Jacket",
    price: 24.99,
    originalPrice: 39.99,
    discount: 38,
    image: "/images/jacket.png",
    category: "kids-clothes",
    inStock: true,
    rating: 5,
    reviews: 18,
  },
  {
    id: "kids-clothes-4",
    name: "Kids' Light-Up Sneakers",
    price: 29.99,
    originalPrice: 44.99,
    discount: 33,
    image: "/images/light.png",
    category: "kids-clothes",
    inStock: true,
    rating: 5,
    reviews: 24,
  },
]

// Keep the old sampleProducts for backward compatibility
export const sampleProducts: Product[] = allProducts.slice(0, 6)

export const getProductsByCategory = (category: string): Product[] => {
  return allProducts.filter((product) => product.category === category)
}

// Best Sellers - Different products (high ratings and reviews)
export const getTrendingProducts = (): Product[] => {
  return [
    allProducts.find((p) => p.id === "beverages-2"), // Coca-Cola - 5 stars, 35 reviews
    allProducts.find((p) => p.id === "electronics-2"), // Oreo - 5 stars, 45 reviews
    allProducts.find((p) => p.id === "women-clothes-3"), // Charmin - 5 stars, 41 reviews
    allProducts.find((p) => p.id === "snacks-8"), // Snickers - 5 stars, 42 reviews
  ].filter(Boolean) as Product[]
}

// Special Offers - Only 8 products with high discounts (25%+)
export const getOfferProducts = (): Product[] => {
  return [
    allProducts.find((p) => p.id === "beverages-1"), // Coffee Creamer - 50% off
    allProducts.find((p) => p.id === "electronics-2"), // Earbuds - 40% off
    allProducts.find((p) => p.id === "women-clothes-4"), // Running Shoes - 39% off
    allProducts.find((p) => p.id === "men-clothes-4"), // Sneakers - 38% off
    allProducts.find((p) => p.id === "kids-clothes-3"), // Winter Jacket - 38% off
    allProducts.find((p) => p.id === "electronics-1"), // USB Cable - 35% off
    allProducts.find((p) => p.id === "stationary-1"), // Pens - 33% off
    allProducts.find((p) => p.id === "electronics-3"), // Phone Charger - 33% off
  ].filter(Boolean) as Product[]
}

// Function to add new products easily
export const addProduct = (product: Product): void => {
  allProducts.push(product)
}
